services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=sigrid.thaler@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  nuxt:
    build:
      context: ./nuxt
      dockerfile: Dockerfile.nuxt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt.rule=Host(`kraeuterakademie.it`,`www.kraeuterakademie.it`)"
      - "traefik.http.routers.nuxt.entrypoints=websecure"
      - "traefik.http.routers.nuxt.tls.certresolver=letsencrypt"
    ports:
      - "3000:3000"
    networks:
      - default
    environment:
      - STRAPI_API_URL=${STRAPI_API_URL}
    depends_on:
      - strapi

  storybook:
    build:
      context: ./nuxt
      dockerfile: Dockerfile.storybook
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storybook.rule=Host(`storybook.kraeuterakademie.it`)"
      - "traefik.http.routers.storybook.entrypoints=websecure"
      - "traefik.http.routers.storybook.tls.certresolver=letsencrypt"
    ports:
      - "6006:6006"
    networks:
      - default
    
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`api.kraeuterakademie.it`)"
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.routers.strapi.tls.certresolver=letsencrypt"
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/app
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_HOST=database
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - HOST=${STRAPI_HOST}
      - APP_KEYS=${STRAPI_APP_KEYS}
      - API_TOKEN_SALT=${STRAPI_API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${STRAPI_ADMIN_JWT_SECRET}
      - JWT_SECRET=${STRAPI_JWT_SECRET}
      - ENCRYPTION_KEY=${STRAPI_ENCRYPTION_KEY}
    depends_on:
      - database
    networks:
      - default

  database:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

volumes:
  postgres-data:
    driver: local

networks:
  default:
    name: kraeuterakademie
    driver: bridge