services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      GH_TOKEN: ${GH_TOKEN}
      HCLOUD_API_TOKEN: ${HCLOUD_API_TOKEN}
    env_file:
      - path: ./.env
        required: true
    volumes:
      - ../:/workspace
      # Mount the setup.sh script to the container
      - ./setup.sh:/root/setup.sh
      # Mount Strapi uploads volume
      - strapi-uploads:/srv/app/public/uploads
    ports:
      - 1337:1337
      - 3000:3000
      - 3001:3001
    networks:
      - default
    command: ["sleep", "infinity"]

  database:
    image: postgres:18
    restart: always
    environment:
      DATABASE_NAMES: ${DATABASE_NAMES}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
      - ../scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 5432:5432
    networks:
      - default

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres
  strapi-uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/strapi-uploads

networks:
  default:
    name: devcontainer
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: devcontainer
