services:
  nuxt:
    build:
      context: .
      dockerfile: nuxt/Dockerfile
    depends_on:
        - database
    environment:
      DB_HOST: ${DATABASE_HOST}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_DB: ${DATABASE_NAME}
    env_file:
      - path: ./nuxt/.env
        required: true
    volumes:
      - ../:/workspace
      # Mount the SSH keys from the host to the container for git access
      - ~/.ssh:/root/.ssh
      # Mount the setup.sh script to the container
      - ./nuxt/setup.sh:/root/setup.sh
    ports:
      - 3000:3000
    networks:
      - default
    command: ["sleep", "infinity"]

  strapi:
    build:
      context: .
      dockerfile: strapi/Dockerfile
    depends_on:
        - database
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    env_file:
      - path: ./strapi/.env
        required: true
    volumes:
      - ../:/workspace
      # Mount the SSH keys from the host to the container for git access
      - ~/.ssh:/root/.ssh
      # Mount the setup.sh script to the container
      - ./strapi/setup.sh:/root/setup.sh
    ports:
      - 1337:1337
    networks:
      - default
    command: ["sleep", "infinity"]

  database:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default

volumes:
  postgres-data:

networks:
  default:
    name: devcontainer
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: devcontainer